import os

from dotenv import load_dotenv

load_dotenv()


class Config:
    SUPABASE_URL = os.environ["SUPABASE_URL"]
    SUPABASE_ANON_KEY = os.environ["SUPABASE_ANON_KEY"]
    SUPABASE_SERVICE_ROLE_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
    ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", "http://localhost:8081").split(",")

    # Quiz reward rules — single source of truth (architecture.md §8). Tunable via env
    # so ratios are never hardcoded in business logic.
    QUIZ_CORRECT_TARGET = int(os.getenv("QUIZ_CORRECT_TARGET", "5"))
    REWARD_SECONDS = int(os.getenv("REWARD_SECONDS", "900"))
    QUIZ_LEN_NORMAL = int(os.getenv("QUIZ_LEN_NORMAL", "5"))
    QUIZ_LEN_DEBT = int(os.getenv("QUIZ_LEN_DEBT", "7"))

    # AI quiz generation. The key is optional: when absent, the generator serves the
    # offline question bank so the whole flow works without a paid dependency. When set,
    # questions are generated by Claude and validated before use (app/ai/generator.py).
    ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY") or None
    ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-haiku-4-5")
    # One automated re-prompt on malformed output, then fall back to the offline bank.
    QUIZ_GEN_RETRIES = int(os.getenv("QUIZ_GEN_RETRIES", "1"))
    # Cap on stored study text per imported material (POST /knowledge/import).
    KNOWLEDGE_MAX_CHARS = int(os.getenv("KNOWLEDGE_MAX_CHARS", "12000"))


class DevelopmentConfig(Config):
    DEBUG = True


class ProductionConfig(Config):
    DEBUG = False


configs = {
    "development": DevelopmentConfig,
    "production": ProductionConfig,
}


def get_config():
    env = os.getenv("FLASK_ENV", "development")
    return configs.get(env, DevelopmentConfig)
