import os

from dotenv import load_dotenv

load_dotenv()


class Config:
    SUPABASE_URL = os.environ["SUPABASE_URL"]
    SUPABASE_ANON_KEY = os.environ["SUPABASE_ANON_KEY"]
    SUPABASE_SERVICE_ROLE_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
    ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", "http://localhost:8081").split(",")

    # Quiz reward rules — single source of truth (architecture.md §8). Tunable via env
    # so ratios are never hardcoded in business logic.
    QUIZ_CORRECT_TARGET = int(os.getenv("QUIZ_CORRECT_TARGET", "5"))
    REWARD_SECONDS = int(os.getenv("REWARD_SECONDS", "900"))
    QUIZ_LEN_NORMAL = int(os.getenv("QUIZ_LEN_NORMAL", "5"))
    QUIZ_LEN_DEBT = int(os.getenv("QUIZ_LEN_DEBT", "7"))

    # AI quiz generation. The key is optional: when absent, the generator serves the
    # offline question bank so the whole flow works without a paid dependency. When set,
    # questions are generated by Claude and validated before use (app/ai/generator.py).
    ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY") or None
    ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-haiku-4-5")
    # One automated re-prompt on malformed output, then fall back to the offline bank.
    QUIZ_GEN_RETRIES = int(os.getenv("QUIZ_GEN_RETRIES", "1"))
    # Cap on stored study text per imported material (POST /knowledge/import).
    KNOWLEDGE_MAX_CHARS = int(os.getenv("KNOWLEDGE_MAX_CHARS", "12000"))
    # Uploaded material files (source_type=file): the max decoded file size accepted,
    # and the output budget for transcribing it to text (app/ai/extractor.py). A
    # worksheet or a photo of a page sits well under 7 MB; the model reads it to text.
    KNOWLEDGE_FILE_MAX_BYTES = int(os.getenv("KNOWLEDGE_FILE_MAX_BYTES", "7000000"))
    KNOWLEDGE_EXTRACT_MAX_TOKENS = int(
        os.getenv("KNOWLEDGE_EXTRACT_MAX_TOKENS", "8000")
    )
    # Only the first N pages of an uploaded PDF are read. The model caps PDFs at 100
    # pages, and the stored text is capped at KNOWLEDGE_MAX_CHARS anyway (a couple dozen
    # pages fills it), so a long lecture deck still works instead of erroring.
    KNOWLEDGE_PDF_MAX_PAGES = int(os.getenv("KNOWLEDGE_PDF_MAX_PAGES", "20"))
    # Bounds on server-side link fetching (issue #12): a slow/huge page must not hang or
    # blow up memory on a request thread.
    KNOWLEDGE_FETCH_TIMEOUT_SECONDS = float(
        os.getenv("KNOWLEDGE_FETCH_TIMEOUT_SECONDS", "10")
    )
    KNOWLEDGE_FETCH_MAX_BYTES = int(os.getenv("KNOWLEDGE_FETCH_MAX_BYTES", "2000000"))
    # Global request body cap (Flask reads this key name automatically) — protects every
    # endpoint from oversized payloads. Sized to admit a base64-encoded material file
    # (KNOWLEDGE_FILE_MAX_BYTES ~7 MB inflates ~33% + JSON overhead); the file endpoint
    # additionally rejects anything over the decoded byte cap.
    MAX_CONTENT_LENGTH = int(os.getenv("MAX_CONTENT_LENGTH", "12000000"))
    # Wake-Up Lock (issue #8) — informational for the client (GET /wakeup/status);
    # the questions themselves are generated via the normal POST /quiz/generate.
    WAKEUP_QUESTIONS = int(os.getenv("WAKEUP_QUESTIONS", "3"))


class DevelopmentConfig(Config):
    DEBUG = True


class ProductionConfig(Config):
    DEBUG = False


configs = {
    "development": DevelopmentConfig,
    "production": ProductionConfig,
}


def get_config():
    # Fail closed: anything other than an explicit "development" runs without DEBUG,
    # so a deployment that forgets FLASK_ENV never exposes the Werkzeug debugger.
    env = os.getenv("FLASK_ENV", "production")
    return configs.get(env, ProductionConfig)
